name: spherical_panorama
description: "A 360-degree panorama viewer."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  sensors_plus: ^6.0.0
  vector_math: ^2.1.4

flutter: